main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.sorvete_pedido, name="pedido"),
    path('lista', views.pedidos, name='lista_pedidos')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models


class Sorvete(models.Model):

    sabor_creme = (
        ('Açaí', 'Açaí'),
        ('Cupuaçu', 'Cupuaçu')
    )

    sabor = models.CharField(
        max_length=10,
        choices=sabor_creme,
        default='Açaí',
    )

    sabor_cobertura = (
        ('Chocolate', 'Chocolate'),
        ('Morango', 'Morango'),
        ('Caramelo', 'Caramelo'),
        ('Leite Condensado', 'Leite condensado')
    )

    cobertura = models.CharField(
        max_length=20,
        choices=sabor_cobertura,
        default='Leite Condensado',
    )

    tipo_tamanho = (
        ('Pequeno', 'Pequeno'),
        ('Médio', 'Médio'),
        ('Grande', 'Grande'),
        ('Barca', 'Barca')
    )

    tamanho = models.CharField(
        max_length=10,
        choices=tipo_tamanho,
        default='Médio',
    )


    def __str__(self):
        return self.sabor

main/forms.py
from django import forms
from .models import Sorvete

class Sorveteforms(forms.ModelForm):
    class Meta:
        model = Sorvete
        fields = '__all__'

main/views.py
from django.shortcuts import render, redirect
from .forms import Sorveteforms
from .models import Sorvete

def sorvete_pedido(request):
    if request.method == 'POST':
        form = Sorveteforms(request.POST)
        if form.is_valid():
            form.save()
            return redirect('pedido')# redireciona para a pagina de sucesso após salvar
    else:
        form = Sorveteforms()
    return render(request, 'main/index.html', {'form':form})

def pedidos(request):
    query = Sorvete.objects.all()
    return render (request, 'main/lista.html', {'query': query})

main/templates/base.html
{% load static %} <!-- Adicione esta linha no início do arquivo para carregar a tag static -->

<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Descrição da página aqui">

  <title>{% block title %}Título da Página{% endblock %}</title>

  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css">
</head>
<body>
  <header>
    <h1>Loja de Açaí</h1>
    <p>Seu melhor açaí!</p>
  </header>

  <div class="container">
    {% block content %}
    {% endblock %}
  </div>

  <footer>
    &copy; {% now "Y" %} Loja de Açaí. Todos os direitos reservados.
  </footer>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"></script>
</body>

</html>

main/templates/main/index.html
{% extends 'base.html' %}

{% block title %}Formulário de Pedido de Sorvete{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-lg-6">
    <form method="post">
      {% csrf_token %}
    <div class="formulario">
        <label for="id_sabor">Sabor:</label>
        <select name="sabor" id="id_sabor">
            <option value="Açaí">Açaí</option>
            <option value="Cupuaçu">Cupuaçu</option>
        </select><br>

        <label for="id_cobertura">Cobertura:</label>
        <select name="cobertura" id="id_cobertura">
            <option value="Chocolate">Chocolate</option>
            <option value="Morango">Morango</option>
            <option value="Caramelo">Caramelo</option>
            <option value="Leite Condensado">Leite Condensado</option>
        </select><br>

        <label for="id_tamanho">Tamanho:</label>
        <select name="tamanho" id="id_tamanho">
            <option value="Pequeno">Pequeno</option>
            <option value="Médio">Médio</option>
            <option value="Grande">Grande</option>
            <option value="Barca">Barca</option>
        </select><br>
    </div>
      <input type="submit" value="Enviar Pedido" class="btn btn-dark btn-block mt-3" class="letra">
    </form>
  </div>
</div>

<div class="row justify-content-center mt-3">
  <div class="col-lg-2">
    <div class="btn-group" role="group" aria-label="Basic example">
    <a class="btn btn-danger btn-block" href="/lista" role="button">Lista</a>
  </div>
</div>
{% endblock %}

main/templates/main/lista.html
{% extends 'base.html' %}

{% block title %}Lista de Sorvetes{% endblock %}

{% block content %}
<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">Sabor</th>
      <th scope="col">Cobertura</th>
      <th scope="col">Tamanho</th>
    </tr>
  </thead>
  <tbody>
    {% for querys in query %}
    <tr>
      <td>{{ querys.sabor }}</td>
      <td>{{ querys.cobertura }}</td>
      <td>{{ querys.tamanho }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}